version: "3.8"

services:
  blackfire:
    image: blackfire/blackfire:2
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    depends_on:
      - php

  elasticsearch:
    image: elasticsearch:7.13.1
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    tty: true

  maildev:
    image: maildev/maildev
    environment:
        MAILDEV_SMTP_PORT: 25
    depends_on:
      - php
    ports:
      - 1080:1080

  mysql:
    image: mariadb:latest
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build:
      context: ./nginx
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - "443:443"
    volumes:
      # Projects files
      - ${PROJECT_LOCATION}:/var/www/html:rw,delegated
      # Websites configuration
      - ${PROJECT_LOCATION}/docker/local/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      # Logs
      - ${PROJECT_LOCATION}/docker/log/nginx:/var/log/nginx
    depends_on:
      - php
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      # Projects files
      - ${PROJECT_LOCATION}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH socket
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      # Composer cache
      - ${COMPOSER_CACHE_DIR:-~/Library/Caches/composer}:/.composer/cache
    depends_on:
      - mysql
      - redis
      - elasticsearch
    tty: true

  redis:
    build:
      context: ./redis
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    tty: true

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
